# Translations template for swift.
# Copyright (C) 2016 ORGANIZATION
# This file is distributed under the same license as the swift project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2016.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: swift 2.7.1.dev50\n"
"Report-Msgid-Bugs-To: https://bugs.launchpad.net/openstack-i18n/\n"
"POT-Creation-Date: 2016-04-18 06:31+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.2.0\n"

#: swift/account/auditor.py:59
#, python-format
msgid ""
"Since %(time)s: Account audits: %(passed)s passed audit,%(failed)s failed"
" audit"
msgstr ""

#: swift/account/auditor.py:82
msgid "Begin account audit pass."
msgstr ""

#: swift/account/auditor.py:88 swift/container/auditor.py:86
msgid "ERROR auditing"
msgstr ""

#: swift/account/auditor.py:93
#, python-format
msgid "Account audit pass completed: %.02fs"
msgstr ""

#: swift/account/auditor.py:99
msgid "Begin account audit \"once\" mode"
msgstr ""

#: swift/account/auditor.py:104
#, python-format
msgid "Account audit \"once\" mode completed: %.02fs"
msgstr ""

#: swift/account/auditor.py:123
#, python-format
msgid ""
"The total %(key)s for the container (%(total)s) does not match the sum of"
" %(key)s across policies (%(sum)s)"
msgstr ""

#: swift/account/auditor.py:148
#, python-format
msgid "Audit Failed for %(path)s: %(err)s"
msgstr ""

#: swift/account/auditor.py:153
#, python-format
msgid "ERROR Could not get account info %s"
msgstr ""

#: swift/account/reaper.py:139 swift/common/utils.py:2392
#: swift/obj/diskfile.py:361 swift/obj/updater.py:88 swift/obj/updater.py:132
#, python-format
msgid "Skipping %s as it is not mounted"
msgstr ""

#: swift/account/reaper.py:143
msgid "Exception in top-level account reaper loop"
msgstr ""

#: swift/account/reaper.py:146
#, python-format
msgid "Devices pass completed: %.02fs"
msgstr ""

#: swift/account/reaper.py:256
#, python-format
msgid "Beginning pass on account %s"
msgstr ""

#: swift/account/reaper.py:281
#, python-format
msgid "Exception with containers for account %s"
msgstr ""

#: swift/account/reaper.py:288
#, python-format
msgid "Exception with account %s"
msgstr ""

#: swift/account/reaper.py:289
#, python-format
msgid "Incomplete pass on account %s"
msgstr ""

#: swift/account/reaper.py:291
#, python-format
msgid ", %s containers deleted"
msgstr ""

#: swift/account/reaper.py:293
#, python-format
msgid ", %s objects deleted"
msgstr ""

#: swift/account/reaper.py:295
#, python-format
msgid ", %s containers remaining"
msgstr ""

#: swift/account/reaper.py:298
#, python-format
msgid ", %s objects remaining"
msgstr ""

#: swift/account/reaper.py:300
#, python-format
msgid ", %s containers possibly remaining"
msgstr ""

#: swift/account/reaper.py:303
#, python-format
msgid ", %s objects possibly remaining"
msgstr ""

#: swift/account/reaper.py:306
msgid ", return codes: "
msgstr ""

#: swift/account/reaper.py:310
#, python-format
msgid ", elapsed: %.02fs"
msgstr ""

#: swift/account/reaper.py:317
#, python-format
msgid "Account %(account)s has not been reaped since %(time)s"
msgstr ""

#: swift/account/reaper.py:376 swift/account/reaper.py:430
#: swift/account/reaper.py:506 swift/container/updater.py:308
#, python-format
msgid "Exception with %(ip)s:%(port)s/%(device)s"
msgstr ""

#: swift/account/reaper.py:383 swift/account/reaper.py:439
#: swift/account/reaper.py:517
#, python-format
msgid "Timeout Exception with %(ip)s:%(port)s/%(device)s"
msgstr ""

#: swift/account/reaper.py:400
#, python-format
msgid "Exception with objects for container %(container)s for account %(account)s"
msgstr ""

#: swift/account/server.py:276 swift/container/server.py:607
#: swift/obj/server.py:1038
#, python-format
msgid "ERROR __call__ error with %(method)s %(path)s "
msgstr ""

#: swift/common/bufferedhttp.py:206 swift/common/bufferedhttp.py:211
#, python-format
msgid "Error encoding to UTF-8: %s"
msgstr ""

#: swift/common/container_sync_realms.py:60
#: swift/common/container_sync_realms.py:69
#, python-format
msgid "Could not load %r: %s"
msgstr ""

#: swift/common/container_sync_realms.py:82
#, python-format
msgid "Error in %r with mtime_check_interval: %s"
msgstr ""

#: swift/common/db.py:353
#, python-format
msgid "Quarantined %(db_dir)s to %(quar_path)s due to %(exc_hint)s database"
msgstr ""

#: swift/common/db.py:410
msgid "Broker error trying to rollback locked connection"
msgstr ""

#: swift/common/db.py:613
#, python-format
msgid "Invalid pending entry %(file)s: %(entry)s"
msgstr ""

#: swift/common/db_replicator.py:144
#, python-format
msgid "ERROR reading HTTP response from %s"
msgstr ""

#: swift/common/db_replicator.py:208
#, python-format
msgid "Attempted to replicate %(count)d dbs in %(time).5f seconds (%(rate).5f/s)"
msgstr ""

#: swift/common/db_replicator.py:214
#, python-format
msgid "Removed %(remove)d dbs"
msgstr ""

#: swift/common/db_replicator.py:215 swift/obj/replicator.py:517
#, python-format
msgid "%(success)s successes, %(failure)s failures"
msgstr ""

#: swift/common/db_replicator.py:262
#, python-format
msgid "ERROR rsync failed with %(code)s: %(args)s"
msgstr ""

#: swift/common/db_replicator.py:326
#, python-format
msgid "ERROR Bad response %(status)s from %(host)s"
msgstr ""

#: swift/common/db_replicator.py:496 swift/common/db_replicator.py:766
#, python-format
msgid "Quarantining DB %s"
msgstr ""

#: swift/common/db_replicator.py:499
#, python-format
msgid "ERROR reading db %s"
msgstr ""

#: swift/common/db_replicator.py:552
#, python-format
msgid "ERROR Remote drive not mounted %s"
msgstr ""

#: swift/common/db_replicator.py:554
#, python-format
msgid "ERROR syncing %(file)s with node %(node)s"
msgstr ""

#: swift/common/db_replicator.py:593
#, python-format
msgid "ERROR while trying to clean up %s"
msgstr ""

#: swift/common/db_replicator.py:621
msgid "ERROR Failed to get my own IPs?"
msgstr ""

#: swift/common/db_replicator.py:637
#, python-format
msgid "Skipping %(device)s as it is not mounted"
msgstr ""

#: swift/common/db_replicator.py:650
msgid "Beginning replication run"
msgstr ""

#: swift/common/db_replicator.py:655
msgid "Replication run OVER"
msgstr ""

#: swift/common/db_replicator.py:668
msgid "ERROR trying to replicate"
msgstr ""

#: swift/common/internal_client.py:196
#, python-format
msgid "Unexpected response: %s"
msgstr ""

#: swift/common/manager.py:68
msgid "WARNING: Unable to modify file descriptor limit.  Running as non-root?"
msgstr ""

#: swift/common/manager.py:75
msgid "WARNING: Unable to modify memory limit.  Running as non-root?"
msgstr ""

#: swift/common/manager.py:82
msgid "WARNING: Unable to modify max process limit.  Running as non-root?"
msgstr ""

#: swift/common/manager.py:241
msgid ""
"\n"
"user quit"
msgstr ""

#: swift/common/manager.py:278 swift/common/manager.py:630
#, python-format
msgid "No %s running"
msgstr ""

#: swift/common/manager.py:291
#, python-format
msgid "%(server)s (%(pid)s) appears to have stopped"
msgstr ""

#: swift/common/manager.py:304
#, python-format
msgid "Waited %(kill_wait)s seconds for %(server)s to die; killing"
msgstr ""

#: swift/common/manager.py:309 swift/common/manager.py:565
#, python-format
msgid "Signal %(server)s  pid: %(pid)s  signal: %(signal)s"
msgstr ""

#: swift/common/manager.py:321
#, python-format
msgid "Waited %(kill_wait)s seconds for %(server)s to die; giving up"
msgstr ""

#: swift/common/manager.py:506
#, python-format
msgid "Unable to locate config number %(number)s for %(server)s"
msgstr ""

#: swift/common/manager.py:510
#, python-format
msgid "Unable to locate config for %s"
msgstr ""

#: swift/common/manager.py:513
msgid "Found configs:"
msgstr ""

#: swift/common/manager.py:560
#, python-format
msgid "Removing pid file %s with invalid pid"
msgstr ""

#: swift/common/manager.py:571
#, python-format
msgid "Removing pid file %(pid_file)s with wrong pid %(pid)d"
msgstr ""

#: swift/common/manager.py:578
#, python-format
msgid "Removing stale pid file %s"
msgstr ""

#: swift/common/manager.py:581
#, python-format
msgid "No permission to signal PID %d"
msgstr ""

#: swift/common/manager.py:626
#, python-format
msgid "%(server)s #%(number)d not running (%(conf)s)"
msgstr ""

#: swift/common/manager.py:634 swift/common/manager.py:728
#, python-format
msgid "%(server)s running (%(pid)s - %(conf)s)"
msgstr ""

#: swift/common/manager.py:732
#, python-format
msgid "%(server)s running (%(pid)s - %(pid_file)s)"
msgstr ""

#: swift/common/manager.py:737
#, python-format
msgid "%s already started..."
msgstr ""

#: swift/common/manager.py:746
#, python-format
msgid "Running %s once"
msgstr ""

#: swift/common/manager.py:748
#, python-format
msgid "Starting %s"
msgstr ""

#: swift/common/manager.py:755
#, python-format
msgid "%s does not exist"
msgstr ""

#: swift/common/memcached.py:166
#, python-format
msgid "Timeout %(action)s to memcached: %(server)s"
msgstr ""

#: swift/common/memcached.py:169
#, python-format
msgid "Error %(action)s to memcached: %(server)s"
msgstr ""

#: swift/common/memcached.py:194
#, python-format
msgid "Error limiting server %s"
msgstr ""

#: swift/common/request_helpers.py:109
#, python-format
msgid "No policy with index %s"
msgstr ""

#: swift/common/request_helpers.py:456
msgid "ERROR: An error occurred while retrieving segments"
msgstr ""

#: swift/common/utils.py:397
#, python-format
msgid "Unable to locate %s in libc.  Leaving as a no-op."
msgstr ""

#: swift/common/utils.py:591
msgid "Unable to locate fallocate, posix_fallocate in libc.  Leaving as a no-op."
msgstr ""

#: swift/common/utils.py:675
#, python-format
msgid "Unable to perform fsync() on directory %(dir)s: %(err)s"
msgstr ""

#: swift/common/utils.py:1271
#, python-format
msgid "%s: Connection reset by peer"
msgstr ""

#: swift/common/utils.py:1273 swift/common/utils.py:1284
#, python-format
msgid "%(type)s: %(value)s"
msgstr ""

#: swift/common/utils.py:1536
msgid "Connection refused"
msgstr ""

#: swift/common/utils.py:1538
msgid "Host unreachable"
msgstr ""

#: swift/common/utils.py:1540
msgid "Connection timeout"
msgstr ""

#: swift/common/utils.py:1818
msgid "UNCAUGHT EXCEPTION"
msgstr ""

#: swift/common/utils.py:1873
msgid "Error: missing config path argument"
msgstr ""

#: swift/common/utils.py:1878
#, python-format
msgid "Error: unable to locate %s"
msgstr ""

#: swift/common/utils.py:2250
#, python-format
msgid "Unable to read config from %s"
msgstr ""

#: swift/common/utils.py:2256
#, python-format
msgid "Unable to find %(section)s config section in %(conf)s"
msgstr ""

#: swift/common/utils.py:2641
#, python-format
msgid "Invalid X-Container-Sync-To format %r"
msgstr ""

#: swift/common/utils.py:2646
#, python-format
msgid "No realm key for %r"
msgstr ""

#: swift/common/utils.py:2650
#, python-format
msgid "No cluster endpoint for %r %r"
msgstr ""

#: swift/common/utils.py:2659
#, python-format
msgid ""
"Invalid scheme %r in X-Container-Sync-To, must be \"//\", \"http\", or "
"\"https\"."
msgstr ""

#: swift/common/utils.py:2663
msgid "Path required in X-Container-Sync-To"
msgstr ""

#: swift/common/utils.py:2666
msgid "Params, queries, and fragments not allowed in X-Container-Sync-To"
msgstr ""

#: swift/common/utils.py:2671
#, python-format
msgid "Invalid host %r in X-Container-Sync-To"
msgstr ""

#: swift/common/utils.py:2865
msgid "Exception dumping recon cache"
msgstr ""

#: swift/common/wsgi.py:199
#, python-format
msgid "Could not bind to %s:%s after trying for %s seconds"
msgstr ""

#: swift/common/wsgi.py:209
msgid ""
"WARNING: SSL should only be enabled for testing purposes. Use external "
"SSL termination for a production deployment."
msgstr ""

#: swift/common/middleware/catch_errors.py:43
msgid "Error: An error occurred"
msgstr ""

#: swift/common/middleware/cname_lookup.py:146
#, python-format
msgid "Mapped %(given_domain)s to %(found_domain)s"
msgstr ""

#: swift/common/middleware/cname_lookup.py:158
#, python-format
msgid "Following CNAME chain for  %(given_domain)s to %(found_domain)s"
msgstr ""

#: swift/common/middleware/ratelimit.py:248
#, python-format
msgid "Returning 497 because of blacklisting: %s"
msgstr ""

#: swift/common/middleware/ratelimit.py:263
#, python-format
msgid "Ratelimit sleep log: %(sleep)s for %(account)s/%(container)s/%(object)s"
msgstr ""

#: swift/common/middleware/ratelimit.py:271
#, python-format
msgid ""
"Returning 498 for %(meth)s to %(acc)s/%(cont)s/%(obj)s . Ratelimit (Max "
"Sleep) %(e)s"
msgstr ""

#: swift/common/middleware/ratelimit.py:293
msgid "Warning: Cannot ratelimit without a memcached client"
msgstr ""

#: swift/common/middleware/recon.py:85
msgid "Error reading recon cache file"
msgstr ""

#: swift/common/middleware/recon.py:87
msgid "Error parsing recon cache file"
msgstr ""

#: swift/common/middleware/recon.py:89
msgid "Error retrieving recon data"
msgstr ""

#: swift/common/middleware/recon.py:163
msgid "Error listing devices"
msgstr ""

#: swift/common/middleware/recon.py:265
msgid "Error reading ringfile"
msgstr ""

#: swift/common/middleware/recon.py:279
msgid "Error reading swift.conf"
msgstr ""

#: swift/common/middleware/xprofile.py:226
#, python-format
msgid "Error on render profiling results: %s"
msgstr ""

#: swift/common/middleware/x_profile/exceptions.py:25
#, python-format
msgid "Profiling Error: %s"
msgstr ""

#: swift/common/middleware/x_profile/html_viewer.py:306
#, python-format
msgid "method %s is not allowed."
msgstr ""

#: swift/common/middleware/x_profile/html_viewer.py:317
#, python-format
msgid "Can not load profile data from %s."
msgstr ""

#: swift/common/middleware/x_profile/html_viewer.py:369
#: swift/common/middleware/x_profile/html_viewer.py:399
msgid "no log file found"
msgstr ""

#: swift/common/middleware/x_profile/html_viewer.py:392
#, python-format
msgid "Data download error: %s"
msgstr ""

#: swift/common/middleware/x_profile/html_viewer.py:397
msgid "python-matplotlib not installed."
msgstr ""

#: swift/common/middleware/x_profile/html_viewer.py:433
#, python-format
msgid "plotting results failed due to %s"
msgstr ""

#: swift/common/middleware/x_profile/html_viewer.py:444
msgid "The file type are forbidden to access!"
msgstr ""

#: swift/common/middleware/x_profile/html_viewer.py:465
#, python-format
msgid "Can not access the file %s."
msgstr ""

#: swift/common/middleware/x_profile/profile_model.py:128
msgid "odfpy not installed."
msgstr ""

#: swift/container/auditor.py:58
#, python-format
msgid ""
"Since %(time)s: Container audits: %(pass)s passed audit, %(fail)s failed "
"audit"
msgstr ""

#: swift/container/auditor.py:80
msgid "Begin container audit pass."
msgstr ""

#: swift/container/auditor.py:91
#, python-format
msgid "Container audit pass completed: %.02fs"
msgstr ""

#: swift/container/auditor.py:97
msgid "Begin container audit \"once\" mode"
msgstr ""

#: swift/container/auditor.py:102
#, python-format
msgid "Container audit \"once\" mode completed: %.02fs"
msgstr ""

#: swift/container/auditor.py:123
#, python-format
msgid "ERROR Could not get container info %s"
msgstr ""

#: swift/container/server.py:186
#, python-format
msgid ""
"ERROR Account update failed: different  numbers of hosts and devices in "
"request: \"%s\" vs \"%s\""
msgstr ""

#: swift/container/server.py:231
#, python-format
msgid ""
"ERROR Account update failed with %(ip)s:%(port)s/%(device)s (will retry "
"later): Response %(status)s %(reason)s"
msgstr ""

#: swift/container/server.py:240
#, python-format
msgid ""
"ERROR account update failed with %(ip)s:%(port)s/%(device)s (will retry "
"later)"
msgstr ""

#: swift/container/sync.py:218
msgid ""
"Configuration option internal_client_conf_path not defined. Using default"
" configuration, See internal-client.conf-sample for options"
msgstr ""

#: swift/container/sync.py:231
#, python-format
msgid "Unable to load internal client from config: %r (%s)"
msgstr ""

#: swift/container/sync.py:253
msgid "Begin container sync \"once\" mode"
msgstr ""

#: swift/container/sync.py:262
#, python-format
msgid "Container sync \"once\" mode completed: %.02fs"
msgstr ""

#: swift/container/sync.py:270
#, python-format
msgid ""
"Since %(time)s: %(sync)s synced [%(delete)s deletes, %(put)s puts], "
"%(skip)s skipped, %(fail)s failed"
msgstr ""

#: swift/container/sync.py:336
#, python-format
msgid "ERROR %(db_file)s: %(validate_sync_to_err)s"
msgstr ""

#: swift/container/sync.py:390
#, python-format
msgid "ERROR Syncing %s"
msgstr ""

#: swift/container/sync.py:539
#, python-format
msgid "Unknown exception trying to GET: %(account)r %(container)r %(object)r"
msgstr ""

#: swift/container/sync.py:564
#, python-format
msgid "Unauth %(sync_from)r => %(sync_to)r"
msgstr ""

#: swift/container/sync.py:570
#, python-format
msgid ""
"Not found %(sync_from)r => %(sync_to)r                       - object "
"%(obj_name)r"
msgstr ""

#: swift/container/sync.py:577 swift/container/sync.py:584
#, python-format
msgid "ERROR Syncing %(db_file)s %(row)s"
msgstr ""

#: swift/container/updater.py:78
#, python-format
msgid "ERROR:  Failed to get paths to drive partitions: %s"
msgstr ""

#: swift/container/updater.py:92 swift/obj/reconstructor.py:822
#: swift/obj/replicator.py:601 swift/obj/replicator.py:718
#, python-format
msgid "%s is not mounted"
msgstr ""

#: swift/container/updater.py:111
#, python-format
msgid "ERROR with loading suppressions from %s: "
msgstr ""

#: swift/container/updater.py:121
msgid "Begin container update sweep"
msgstr ""

#: swift/container/updater.py:156
#, python-format
msgid ""
"Container update sweep of %(path)s completed: %(elapsed).02fs, "
"%(success)s successes, %(fail)s failures, %(no_change)s with no changes"
msgstr ""

#: swift/container/updater.py:170
#, python-format
msgid "Container update sweep completed: %.02fs"
msgstr ""

#: swift/container/updater.py:182
msgid "Begin container update single threaded sweep"
msgstr ""

#: swift/container/updater.py:190
#, python-format
msgid ""
"Container update single threaded sweep completed: %(elapsed).02fs, "
"%(success)s successes, %(fail)s failures, %(no_change)s with no changes"
msgstr ""

#: swift/container/updater.py:245
#, python-format
msgid "Update report sent for %(container)s %(dbfile)s"
msgstr ""

#: swift/container/updater.py:254
#, python-format
msgid "Update report failed for %(container)s %(dbfile)s"
msgstr ""

#: swift/container/updater.py:296
#, python-format
msgid ""
"ERROR account update failed with %(ip)s:%(port)s/%(device)s (will retry "
"later): "
msgstr ""

#: swift/obj/auditor.py:104
#, python-format
msgid " - parallel, %s"
msgstr ""

#: swift/obj/auditor.py:106
#, python-format
msgid " - %s"
msgstr ""

#: swift/obj/auditor.py:107
#, python-format
msgid "Begin object audit \"%(mode)s\" mode (%(audi_type)s%(description)s)"
msgstr ""

#: swift/obj/auditor.py:138
#, python-format
msgid ""
"Object audit (%(type)s). Since %(start_time)s: Locally: %(passes)d "
"passed, %(quars)d quarantined, %(errors)d errors, files/sec: %(frate).2f,"
" bytes/sec: %(brate).2f, Total time: %(total).2f, Auditing time: "
"%(audit).2f, Rate: %(audit_rate).2f"
msgstr ""

#: swift/obj/auditor.py:172
#, python-format
msgid ""
"Object audit (%(type)s) \"%(mode)s\" mode completed: %(elapsed).02fs. "
"Total quarantined: %(quars)d, Total errors: %(errors)d, Total files/sec: "
"%(frate).2f, Total bytes/sec: %(brate).2f, Auditing time: %(audit).2f, "
"Rate: %(audit_rate).2f"
msgstr ""

#: swift/obj/auditor.py:187
#, python-format
msgid "Object audit stats: %s"
msgstr ""

#: swift/obj/auditor.py:218
#, python-format
msgid "ERROR Trying to audit %s"
msgstr ""

#: swift/obj/auditor.py:258
#, python-format
msgid "ERROR Object %(obj)s failed audit and was quarantined: %(err)s"
msgstr ""

#: swift/obj/auditor.py:319
#, python-format
msgid "ERROR: Unable to run auditing: %s"
msgstr ""

#: swift/obj/auditor.py:397 swift/obj/auditor.py:418
#, python-format
msgid "ERROR auditing: %s"
msgstr ""

#: swift/obj/diskfile.py:370
#, python-format
msgid "Skipping %(dir)s: %(err)s"
msgstr ""

#: swift/obj/diskfile.py:380 swift/obj/updater.py:163
#, python-format
msgid "Directory %r does not map to a valid policy (%s)"
msgstr ""

#: swift/obj/diskfile.py:422
#, python-format
msgid "Cannot read %(auditor_status)s (%(err)s)"
msgstr ""

#: swift/obj/diskfile.py:428
#, python-format
msgid "Loading JSON from %(auditor_status)s failed (%(err)s)"
msgstr ""

#: swift/obj/diskfile.py:444
#, python-format
msgid "Cannot write %(auditor_status)s (%(err)s)"
msgstr ""

#: swift/obj/diskfile.py:918
#, python-format
msgid "Quarantined %(hsh_path)s to %(quar_path)s because it is not a directory"
msgstr ""

#: swift/obj/diskfile.py:1038
msgid "Error hashing suffix"
msgstr ""

#: swift/obj/diskfile.py:1202
#, python-format
msgid "Quarantined %(object_path)s to %(quar_path)s because it is not a directory"
msgstr ""

#: swift/obj/diskfile.py:1455
#, python-format
msgid "Problem cleaning up %s"
msgstr ""

#: swift/obj/diskfile.py:1800
#, python-format
msgid "ERROR DiskFile %(data_file)s close failure: %(exc)s : %(stack)s"
msgstr ""

#: swift/obj/diskfile.py:2128
#, python-format
msgid ""
"Client path %(client)s does not match path stored in object metadata "
"%(meta)s"
msgstr ""

#: swift/obj/diskfile.py:2536
#, python-format
msgid "No space left on device for %(file)s (%(err)s)"
msgstr ""

#: swift/obj/diskfile.py:2545
#, python-format
msgid "Problem cleaning up %(datadir)s (%(err)s)"
msgstr ""

#: swift/obj/diskfile.py:2548
#, python-format
msgid "Problem writing durable state file %(file)s (%(err)s)"
msgstr ""

#: swift/obj/expirer.py:80
#, python-format
msgid "Pass completed in %ds; %d objects expired"
msgstr ""

#: swift/obj/expirer.py:87
#, python-format
msgid "Pass so far %ds; %d objects expired"
msgstr ""

#: swift/obj/expirer.py:171
#, python-format
msgid "Pass beginning; %s possible containers; %s possible objects"
msgstr ""

#: swift/obj/expirer.py:197
#, python-format
msgid "Exception while deleting container %(container)s %(err)s"
msgstr ""

#: swift/obj/expirer.py:203 swift/obj/expirer.py:220
msgid "Unhandled exception"
msgstr ""

#: swift/obj/expirer.py:270
#, python-format
msgid "Exception while deleting object %(container)s %(obj)s %(err)s"
msgstr ""

#: swift/obj/reconstructor.py:213 swift/obj/reconstructor.py:499
#, python-format
msgid "Invalid response %(resp)s from %(full_path)s"
msgstr ""

#: swift/obj/reconstructor.py:221
#, python-format
msgid "Trying to GET %(full_path)s"
msgstr ""

#: swift/obj/reconstructor.py:328
#, python-format
msgid "Error trying to rebuild %(path)s policy#%(policy)d frag#%(frag_index)s"
msgstr ""

#: swift/obj/reconstructor.py:355
#, python-format
msgid ""
"%(reconstructed)d/%(total)d (%(percentage).2f%%) partitions of "
"%(device)d/%(dtotal)d (%(dpercentage).2f%%) devices reconstructed in "
"%(time).2fs (%(rate).2f/sec, %(remaining)s remaining)"
msgstr ""

#: swift/obj/reconstructor.py:376 swift/obj/replicator.py:522
#, python-format
msgid ""
"%(checked)d suffixes checked - %(hashed).2f%% hashed, %(synced).2f%% "
"synced"
msgstr ""

#: swift/obj/reconstructor.py:383 swift/obj/replicator.py:529
#, python-format
msgid "Partition times: max %(max).4fs, min %(min).4fs, med %(med).4fs"
msgstr ""

#: swift/obj/reconstructor.py:391
#, python-format
msgid "Nothing reconstructed for %s seconds."
msgstr ""

#: swift/obj/reconstructor.py:420 swift/obj/replicator.py:566
msgid "Lockup detected.. killing live coros."
msgstr ""

#: swift/obj/reconstructor.py:467
#, python-format
msgid "Trying to sync suffixes with %s"
msgstr ""

#: swift/obj/reconstructor.py:492
#, python-format
msgid "%s responded as unmounted"
msgstr ""

#: swift/obj/reconstructor.py:893 swift/obj/replicator.py:372
#, python-format
msgid "Removing partition: %s"
msgstr ""

#: swift/obj/reconstructor.py:909
msgid "Ring change detected. Aborting current reconstruction pass."
msgstr ""

#: swift/obj/reconstructor.py:928
msgid "Exception in top-levelreconstruction loop"
msgstr ""

#: swift/obj/reconstructor.py:938
msgid "Running object reconstructor in script mode."
msgstr ""

#: swift/obj/reconstructor.py:947
#, python-format
msgid "Object reconstruction complete (once). (%.02f minutes)"
msgstr ""

#: swift/obj/reconstructor.py:954
msgid "Starting object reconstructor in daemon mode."
msgstr ""

#: swift/obj/reconstructor.py:958
msgid "Starting object reconstruction pass."
msgstr ""

#: swift/obj/reconstructor.py:963
#, python-format
msgid "Object reconstruction complete. (%.02f minutes)"
msgstr ""

#: swift/obj/replicator.py:185
#, python-format
msgid "Killing long-running rsync: %s"
msgstr ""

#: swift/obj/replicator.py:199
#, python-format
msgid "Bad rsync return code: %(ret)d <- %(args)s"
msgstr ""

#: swift/obj/replicator.py:206 swift/obj/replicator.py:210
#, python-format
msgid "Successful rsync of %(src)s at %(dst)s (%(time).03f)"
msgstr ""

#: swift/obj/replicator.py:338
#, python-format
msgid "Removing %s objects"
msgstr ""

#: swift/obj/replicator.py:359
msgid "Error syncing handoff partition"
msgstr ""

#: swift/obj/replicator.py:437
#, python-format
msgid "%(ip)s/%(device)s responded as unmounted"
msgstr ""

#: swift/obj/replicator.py:444
#, python-format
msgid "Invalid response %(resp)s from %(ip)s"
msgstr ""

#: swift/obj/replicator.py:488
#, python-format
msgid "Error syncing with node: %s"
msgstr ""

#: swift/obj/replicator.py:493
msgid "Error syncing partition"
msgstr ""

#: swift/obj/replicator.py:508
#, python-format
msgid ""
"%(replicated)d/%(total)d (%(percentage).2f%%) partitions replicated in "
"%(time).2fs (%(rate).2f/sec, %(remaining)s remaining)"
msgstr ""

#: swift/obj/replicator.py:537
#, python-format
msgid "Nothing replicated for %s seconds."
msgstr ""

#: swift/obj/replicator.py:724
msgid ""
"Handoffs first mode still has handoffs remaining.  Aborting current "
"replication pass."
msgstr ""

#: swift/obj/replicator.py:730
msgid "Ring change detected. Aborting current replication pass."
msgstr ""

#: swift/obj/replicator.py:758
msgid "Exception in top-level replication loop"
msgstr ""

#: swift/obj/replicator.py:768
msgid "Running object replicator in script mode."
msgstr ""

#: swift/obj/replicator.py:786
#, python-format
msgid "Object replication complete (once). (%.02f minutes)"
msgstr ""

#: swift/obj/replicator.py:797
msgid "Starting object replicator in daemon mode."
msgstr ""

#: swift/obj/replicator.py:801
msgid "Starting object replication pass."
msgstr ""

#: swift/obj/replicator.py:806
#, python-format
msgid "Object replication complete. (%.02f minutes)"
msgstr ""

#: swift/obj/server.py:241
#, python-format
msgid ""
"ERROR Container update failed (saving for async update later): %(status)d"
" response from %(ip)s:%(port)s/%(dev)s"
msgstr ""

#: swift/obj/server.py:248
#, python-format
msgid ""
"ERROR container update failed with %(ip)s:%(port)s/%(dev)s (saving for "
"async update later)"
msgstr ""

#: swift/obj/server.py:284
#, python-format
msgid ""
"ERROR Container update failed: different numbers of hosts and devices in "
"request: \"%s\" vs \"%s\""
msgstr ""

#: swift/obj/updater.py:63
#, python-format
msgid "ERROR: Unable to access %(path)s: %(error)s"
msgstr ""

#: swift/obj/updater.py:78
msgid "Begin object update sweep"
msgstr ""

#: swift/obj/updater.py:105
#, python-format
msgid ""
"Object update sweep of %(device)s completed: %(elapsed).02fs, %(success)s"
" successes, %(fail)s failures"
msgstr ""

#: swift/obj/updater.py:114
#, python-format
msgid "Object update sweep completed: %.02fs"
msgstr ""

#: swift/obj/updater.py:123
msgid "Begin object update single threaded sweep"
msgstr ""

#: swift/obj/updater.py:137
#, python-format
msgid ""
"Object update single threaded sweep completed: %(elapsed).02fs, "
"%(success)s successes, %(fail)s failures"
msgstr ""

#: swift/obj/updater.py:181
#, python-format
msgid "ERROR async pending file with unexpected name %s"
msgstr ""

#: swift/obj/updater.py:211
#, python-format
msgid "ERROR Pickle problem, quarantining %s"
msgstr ""

#: swift/obj/updater.py:276
#, python-format
msgid "ERROR with remote server %(ip)s:%(port)s/%(device)s"
msgstr ""

#: swift/proxy/server.py:418
msgid "ERROR Unhandled exception in request"
msgstr ""

#: swift/proxy/server.py:473
#, python-format
msgid "Node error limited %(ip)s:%(port)s (%(device)s)"
msgstr ""

#: swift/proxy/server.py:490 swift/proxy/server.py:508
#, python-format
msgid "%(msg)s %(ip)s:%(port)s/%(device)s"
msgstr ""

#: swift/proxy/server.py:531
#, python-format
msgid "ERROR with %(type)s server %(ip)s:%(port)s/%(device)s re: %(info)s"
msgstr ""

#: swift/proxy/controllers/account.py:67
msgid "Account"
msgstr ""

#: swift/proxy/controllers/base.py:813 swift/proxy/controllers/base.py:852
#: swift/proxy/controllers/base.py:948 swift/proxy/controllers/obj.py:340
#: swift/proxy/controllers/obj.py:885 swift/proxy/controllers/obj.py:934
#: swift/proxy/controllers/obj.py:948 swift/proxy/controllers/obj.py:1764
#: swift/proxy/controllers/obj.py:2003 swift/proxy/controllers/obj.py:2166
#: swift/proxy/controllers/obj.py:2400
msgid "Object"
msgstr ""

#: swift/proxy/controllers/base.py:814 swift/proxy/controllers/base.py:853
msgid "Trying to read during GET (retrying)"
msgstr ""

#: swift/proxy/controllers/base.py:949
msgid "Trying to read during GET"
msgstr ""

#: swift/proxy/controllers/base.py:953
#, python-format
msgid "Client did not read from proxy within %ss"
msgstr ""

#: swift/proxy/controllers/base.py:958
msgid "Client disconnected on read"
msgstr ""

#: swift/proxy/controllers/base.py:960
msgid "Trying to send to client"
msgstr ""

#: swift/proxy/controllers/base.py:1002 swift/proxy/controllers/base.py:1441
#, python-format
msgid "Trying to %(method)s %(path)s"
msgstr ""

#: swift/proxy/controllers/base.py:1041 swift/proxy/controllers/base.py:1429
#: swift/proxy/controllers/obj.py:364 swift/proxy/controllers/obj.py:925
#: swift/proxy/controllers/obj.py:2158 swift/proxy/controllers/obj.py:2445
msgid "ERROR Insufficient Storage"
msgstr ""

#: swift/proxy/controllers/base.py:1044
#, python-format
msgid "ERROR %(status)d %(body)s From %(type)s Server"
msgstr ""

#: swift/proxy/controllers/base.py:1432
#, python-format
msgid "ERROR %(status)d Trying to %(method)s %(path)sFrom Container Server"
msgstr ""

#: swift/proxy/controllers/base.py:1562
#, python-format
msgid "%(type)s returning 503 for %(statuses)s"
msgstr ""

#: swift/proxy/controllers/container.py:100
msgid "Container"
msgstr ""

#: swift/proxy/controllers/obj.py:341
#, python-format
msgid "Trying to get final status of PUT to %s"
msgstr ""

#: swift/proxy/controllers/obj.py:368 swift/proxy/controllers/obj.py:2450
#, python-format
msgid "ERROR %(status)d %(body)s From Object Server re: %(path)s"
msgstr ""

#: swift/proxy/controllers/obj.py:579
#, python-format
msgid "Object PUT returning 412, %(statuses)r"
msgstr ""

#: swift/proxy/controllers/obj.py:592
#, python-format
msgid "Object PUT returning 202 for 409: %(req_timestamp)s <= %(timestamps)r"
msgstr ""

#: swift/proxy/controllers/obj.py:929 swift/proxy/controllers/obj.py:2161
#, python-format
msgid "ERROR %(status)d Expect: 100-continue From Object Server"
msgstr ""

#: swift/proxy/controllers/obj.py:935 swift/proxy/controllers/obj.py:2167
#, python-format
msgid "Expect: 100-continue on %s"
msgstr ""

#: swift/proxy/controllers/obj.py:949 swift/proxy/controllers/obj.py:1765
#, python-format
msgid "Trying to write to %s"
msgstr ""

#: swift/proxy/controllers/obj.py:1000 swift/proxy/controllers/obj.py:2332
#, python-format
msgid "ERROR Client read timeout (%ss)"
msgstr ""

#: swift/proxy/controllers/obj.py:1008 swift/proxy/controllers/obj.py:2338
msgid "Client disconnected without sending last chunk"
msgstr ""

#: swift/proxy/controllers/obj.py:1013 swift/proxy/controllers/obj.py:2345
msgid "ERROR Exception causing client disconnect"
msgstr ""

#: swift/proxy/controllers/obj.py:1017 swift/proxy/controllers/obj.py:2349
#, python-format
msgid "ERROR Exception transferring data to object servers %s"
msgstr ""

#: swift/proxy/controllers/obj.py:1023 swift/proxy/controllers/obj.py:2263
msgid "Client disconnected without sending enough data"
msgstr ""

#: swift/proxy/controllers/obj.py:1069
#, python-format
msgid "Object servers returned %s mismatched etags"
msgstr ""

#: swift/proxy/controllers/obj.py:1073 swift/proxy/controllers/obj.py:2309
#: swift/proxy/controllers/obj.py:2534
msgid "Object PUT"
msgstr ""

#: swift/proxy/controllers/obj.py:2302
#, python-format
msgid "Not enough object servers ack'ed (got %d)"
msgstr ""

#: swift/proxy/controllers/obj.py:2401
#, python-format
msgid "Trying to get %(status_type)s status of PUT to %(path)s"
msgstr ""

